### ISSUE TITLE
onShow callback

### ISSUE THREAD

**Issue by jgallen23** [firstandthird/wait#3]
I want to be able to hook in something like [spin.js](http://fgnass.github.io/spin.js/).  I was thinking something like this:

```
wait.show({
    title: 'Loading...',
    onShow: function(element) {
       //element == wait element
       element.append(spinjs)
    }
});
```

thoughts @Belelros ?

**Comment by Antonio-Laguna** [comment]
That's nice! I'll implement it as well as onHide :+1:
